import { BenchmarkInstanceConfig } from './benchmark.types';

export const DEFAULT_SUPERBIKE: BenchmarkInstanceConfig = {
  id: 'instance-1',
  name: 'Superbike 1000cc',
  enabled: true,
  colorAccent: '#F2554A', // Coral (series-1)
  spriteKey: 'ninja',
  vehicle: {
    mass: 205.0,
    wheelbase: 1.42,
    cogDistanceFront: 0.72,
    cogDistanceRear: 0.70,
    cogHeight: 0.58,
    wheelRadius: 0.31,
    wheelInertia: 0.65,
    dragCoefficient: 0.58,
    frontalArea: 0.65,
    brakeBiasRatio: 0.25,
  },
  brake: {
    brakeType: 'disc',
    rotorMass: 1.60,
    specificHeat: 460.0,
    surfaceArea: 0.055,
    pistonArea: 0.0016,
    effectiveRadius: 0.135,
    padFrictionNominal: 0.45,
    fadeTemperature: 280.0,
    fadeCoefficient: 0.005,
    fluidBoilTemperature: 240.0,
    vaporTransitionBand: 20.0,
    thermalEfficiency: 0.90,
    drumAmplification: 1.0,
  },
  actuation: {
    type: 'progressive_squeeze',
    targetPressure: 6.0e6,
    riseTime: 0.40,
  },
  environment: {
    substrate: 'asphalt',
    contaminant: 'dry',
    roadGradeAngle: 0.0,
    curveRadius: Infinity,
    potholeEnabled: false,
    ambientTemperature: 25.0,
    airDensity: 1.225,
  },
  simulation: {
    initialVelocity: 22.22, // 80 km/h
    initialRotorTemp: 35.0,
    hazardDistance: 55.0,
    maxSimulationTime: 8.0,
    numTelemetryPoints: 150,
    standstillCutoffVelocity: 0.05,
    lowSpeedEpsilon: 0.10,
  },
};

export const DEFAULT_CRUISER: BenchmarkInstanceConfig = {
  id: 'instance-2',
  name: 'Cruiser 650cc',
  enabled: false,
  colorAccent: '#2E2C33', // Ink Charcoal (series-2)
  spriteKey: 'cruiser',
  vehicle: {
    mass: 260.0,
    wheelbase: 1.58,
    cogDistanceFront: 0.85,
    cogDistanceRear: 0.73,
    cogHeight: 0.52,
    wheelRadius: 0.33,
    wheelInertia: 0.82,
    dragCoefficient: 0.68,
    frontalArea: 0.80,
    brakeBiasRatio: 0.45,
  },
  brake: {
    brakeType: 'disc',
    rotorMass: 1.80,
    specificHeat: 460.0,
    surfaceArea: 0.050,
    pistonArea: 0.0014,
    effectiveRadius: 0.130,
    padFrictionNominal: 0.38,
    fadeTemperature: 250.0,
    fadeCoefficient: 0.006,
    fluidBoilTemperature: 220.0,
    vaporTransitionBand: 20.0,
    thermalEfficiency: 0.90,
    drumAmplification: 1.0,
  },
  actuation: {
    type: 'progressive_squeeze',
    targetPressure: 5.0e6,
    riseTime: 0.55,
  },
  environment: {
    substrate: 'asphalt',
    contaminant: 'dry',
    roadGradeAngle: 0.0,
    curveRadius: Infinity,
    potholeEnabled: false,
    ambientTemperature: 25.0,
    airDensity: 1.225,
  },
  simulation: {
    initialVelocity: 22.22, // 80 km/h
    initialRotorTemp: 30.0,
    hazardDistance: 55.0,
    maxSimulationTime: 8.0,
    numTelemetryPoints: 150,
    standstillCutoffVelocity: 0.05,
    lowSpeedEpsilon: 0.10,
  },
};

export const DEFAULT_SCOOTER: BenchmarkInstanceConfig = {
  id: 'instance-3',
  name: 'Urban Scooter 125cc',
  enabled: false,
  colorAccent: '#6F8FAF', // Slate Blue (series-3)
  spriteKey: 'scooter',
  vehicle: {
    mass: 130.0,
    wheelbase: 1.28,
    cogDistanceFront: 0.60,
    cogDistanceRear: 0.68,
    cogHeight: 0.50,
    wheelRadius: 0.25,
    wheelInertia: 0.35,
    dragCoefficient: 0.75,
    frontalArea: 0.60,
    brakeBiasRatio: 0.50,
  },
  brake: {
    brakeType: 'drum',
    rotorMass: 1.10,
    specificHeat: 480.0,
    surfaceArea: 0.035,
    pistonArea: 0.0010,
    effectiveRadius: 0.105,
    padFrictionNominal: 0.32,
    fadeTemperature: 200.0,
    fadeCoefficient: 0.008,
    fluidBoilTemperature: 190.0,
    vaporTransitionBand: 25.0,
    thermalEfficiency: 0.85,
    drumAmplification: 1.8,
  },
  actuation: {
    type: 'sudden_lockup',
    targetPressure: 4.5e6,
    riseTime: 0.10,
  },
  environment: {
    substrate: 'asphalt',
    contaminant: 'dry',
    roadGradeAngle: 0.0,
    curveRadius: Infinity,
    potholeEnabled: false,
    ambientTemperature: 25.0,
    airDensity: 1.225,
  },
  simulation: {
    initialVelocity: 16.67, // 60 km/h
    initialRotorTemp: 25.0,
    hazardDistance: 55.0,
    maxSimulationTime: 8.0,
    numTelemetryPoints: 150,
    standstillCutoffVelocity: 0.05,
    lowSpeedEpsilon: 0.10,
  },
};
